sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

before_script:
  - sh -c "sed -i -e s%'smtp'%'log'% config/mail.php"
  - composer self-update
  - touch storage/database.sqlite
  - cp .env.testing .env
  - composer install --prefer-source
  - php artisan migrate
  - sh -c "sed -i -e s%\<\?php%\<\?php\ include\ \'../c3.php\'\;% public/index.php"
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run --coverage-xml

after_script:
  - cat tests/_output/*.fail.html
  - wget https://scrutinizer-ci.com/ocular.phar
  - mv tests/_output/coverage.xml tests/_output/coverage.clover
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.clover
